apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: flag-guessing-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-username/flag-guessing-game-backend:latest
        ports:
        - containerPort: 3501
        envFrom:
        - configMapRef:
            name: flag-game-config
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: flag-game-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flag-game-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: flag-game-secrets
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3501
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      initContainers:
      - name: migrate
        image: ghcr.io/your-username/flag-guessing-game-backend:latest
        command: ["npm", "run", "migrate:prod"]
        envFrom:
        - configMapRef:
            name: flag-game-config
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: flag-game-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flag-game-secrets
              key: DB_PASSWORD
      - name: seed
        image: ghcr.io/your-username/flag-guessing-game-backend:latest
        command: ["npm", "run", "seed:flags:prod"]
        envFrom:
        - configMapRef:
            name: flag-game-config
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: flag-game-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flag-game-secrets
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: flag-guessing-game
spec:
  selector:
    app: backend
  ports:
  - port: 3501
    targetPort: 3501
  type: ClusterIP